# Drupal 8/9 GitLab CI

# Custom docker image based off the stock PHP one, includes Drupal dependencies
# and testing dependencies.
# See details here: https://github.com/smmccabe/docker/blob/master/Dockerfile
image: git.acromedia.com:4567/acro/code/docker:latest

# Include the Acro Standards templates.
# Remove whichever are not needed and relevant jobs below.
include:
  - project: 'acro/code/standards'
    ref: master
    file:
      - '/ci-templates/variables.yml'
      - '/ci-templates/jobs/phpunit-coverage.yml'
      - '/ci-templates/jobs/build.yml'
      - '/ci-templates/jobs/code-standards.yml'
      - '/ci-templates/jobs/config-test.yml'
      - '/ci-templates/jobs/deploy.yml'
      - '/ci-templates/jobs/load-timer.yml'
      - '/ci-templates/jobs/node-tests.yml'
      - '/ci-templates/jobs/php-debt.yml'
      - '/ci-templates/jobs/security-advisories.yml'

  - template: Code-Quality.gitlab-ci.yml

# These cover all the stages used in the standard templates.
stages:
  - build # Builds site and installs dependencies
  - test # Runs tests such as PHPCS and PHPUnit
  - deploy # Deploys to Sites
  - post # Any checks or extras that need to happen

# Defines all the variables used through the CI.
# Barring edge cases, this is all you should have to edit.
variables:
  extends: .default-variables

  # Overrides
  ###########
  # Note all vars that NEED to be overridden are here.
  # Definitions can be found in the variables.yml file.
  SITE_NAME: mySite
  THEME_NAME: myTheme

  SETTINGS_OWNER: account:group

  PROJECT_ROOT: /home/ACCOUNT_NAME/www/PROJECT_NAME

  # Needed for 'node-tests'.
  NODE_APP_ROOT:  /nodeAppRoot

  # This defaults to 'web/core/phpunit.xml.dist' if omitted here.
  PHPUNIT_FILE: $PROJECT_ROOT/phpunit.xml

  PRODUCTION_SSH_DESTINATION: acro@mysite.com
  STAGING_SSH_DESTINATION: acro@mysite.stage.com

  PRODUCTION_URL: https://mysite.com
  STAGING_URL: https://mysite.stage.com

#############
# Build Stage
#############

build:
  extends: .build

############
# Test Stage
############

automated-tests:
  extends: .phpunit-coverage

code-standards:
  extends: .code-standards

#config-test-production:
#  extends: .config-test
#
#  only:
#    - master
#
#  environment:
#    name: production
#    url: $PRODUCTION_URL
#
#  variables:
#    SSH_DESTINATION: $PRODUCTION_SSH_DESTINATION

#config-test-staging:
#  extends: .config-test
#
#  only:
#    - staging
#
#  environment:
#    name: staging
#    url: $STAGING_URL
#
#  variables:
#    SSH_DESTINATION: $STAGING_SSH_DESTINATION

node-test:
  extends: .node-tests

php-debt:
  extends: .php-debt

security-advisories:
  extends: .security-advisories

##############
# Deploy Stage
##############

# Staging
#########

#deploy-staging:
#  extends: .deploy
#
#  only:
#    - staging
#
#  environment:
#    name: staging
#    url: $STAGING_URL
#
#  variables:
#    SSH_DESTINATION: $STAGING_SSH_DESTINATION

# Production
############

#deploy-production:
#  extends: .deploy
#
#  only:
#    - master
#
#  environment:
#    name: production
#    url: $PRODUCTION_URL
#
#  variables:
#    SSH_DESTINATION: $PRODUCTION_SSH_DESTINATION


############
# Post Stage
############

load-timer-staging:
  extends: .load-timer

  only:
    - staging

  variables:
    LOAD_URL: $STAGING_URL

load-timer-production:
  extends: .load-timer

  only:
    - master

  variables:
    LOAD_URL: $PRODUCTION_URL

pages:
  stage: post
  dependencies:
    - automated-tests
  script:
    - mkdir public
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

##################
# Common Templates
##################

# Config Test
# Replace TYPE with the correct name (I.E. production).
#############
# config-test-TYPE:
#   extends: .config-test
#
#   only:
#     - TYPE branch
#
#   environment:
#     name: TYPE
#     url: $TYPE_URL
#
#  variables:
#     SSH_DESTINATION: $TYPE_SSH_DESTINATION

# Deploy
# Replace TYPE with the correct name (I.E. production).
########
# deploy-TYPE:
#   extends: .deploy
#
#   only:
#     - TYPE branch
#
#   environment:
#     name: TYPE
#     url: $TYPE_URL
#
#   variables:
#     SSH_DESTINATION: $TYPE_SSH_DESTINATION

# Load Timer
# Replace TYPE with the correct name (I.E. production).
############
# load-timer-TYPE:
#  extends: .load-timer
#
#  only:
#    - TYPE branch
#
#  variables:
#    LOADTIMER_URL: $TYPE_URL
